AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS X-Ray SDK Layer

Resources:
  SDKlayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWS-X-RAY-SDK-v3_2_0
      Description: AWS-X-RAY-SDK-v3_2_0
      ContentUri: ./layer
      CompatibleRuntimes:
        - nodejs16.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
    
